rounded-corners = 1;
corner-radius = 10;
animations = true;

animation-for-open-window = "zoom";
animation-for-close-window = "zoom";
animation-for-unmap-window = "fade-out";
animation-for-map-window = "fade-in";

animation-stiffness = 200;
animation-dampening = 25;
animation-clamping = true;
